### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-monit#1]
### Type of Report

Review Request

### Actual behaviour

Role had no initial review.

### Expected behaviour

Role must be reviewed and commented.

**Comment by Cinux90** [comment]
two points from my side:

- why no default values for are not set? For me its should be good to provide any initial values:
  - wtd_monit_pidfile
  - wtd_monit_idfile
  - wtd_monit_statefile

- folder files and vars are empty -> can be deleted from my side
- looked into the monitrc. looks valid from my side, but i'm not familiar with monit because never used.

**Comment by daniel-schier** [comment]
thanks a lot

in monit these values are unset per default. its weird, but thats how it is :(

Other stuff is done in #2
